# Generated by Django 5.1.3 on 2025-07-11 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_type', models.CharField(choices=[('PSY', 'Psychiatrist'), ('COU', 'Counselor'), ('LCSW', 'Clinical Social Worker')], max_length=50)),
                ('bio', models.TextField()),
                ('qualifications', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=200)),
                ('experience_years', models.PositiveIntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='experts/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
